### ISSUE TITLE
How do I add fog simulation to my dataset

### ISSUE THREAD

**Issue by lcl124252** [MartinHahner/LiDAR_fog_sim#16]
Can I only use the dataset in the introduction of the code, what if I want to add this fog simulation to my dataset?

**Comment by yinheyanxian** [comment]
I have the same problem. Have you solved it？

**Comment by SakuraTau** [comment]
> I have the same problem. Have you solved it？我也有同样的问题。你解决了吗？

I have the same problem. Have you solved it？
