### ISSUE TITLE
Point cloud fog visualization problem 

### ISSUE THREAD

**Issue by gabigarmus** [MartinHahner/LiDAR_fog_sim#18]
Hello. I ran the simulation but a point cloud fog visualization problem happened. It seems that point cloud fog is in another axis and I don't know why, because I followed the setup steps. Also I can't change the parameters. Could you help me?

![fog simulation 2](https://github.com/MartinHahner/LiDAR_fog_sim/assets/112777068/aadb4c9b-5ec2-4651-a02f-4ded1a7f6988)
![fog simulation](https://github.com/MartinHahner/LiDAR_fog_sim/assets/112777068/fdce2e4b-9e74-4dc4-bc98-780ea6257469)
![fog simulation 3](https://github.com/MartinHahner/LiDAR_fog_sim/assets/112777068/601a0c2e-6b17-4256-82ec-0cc6a5ca6456)

**Comment by gabigarmus** [comment]
Which dataset do you used and what sequence do you had done?

**Comment by MartinHahner** [comment]
https://github.com/MartinHahner/LiDAR_fog_sim?tab=readme-ov-file#overview

**Comment by gabigarmus** [comment]
When you used the KITTI dataset it worked for you? because my screenprint above were KITTI dataset.

**Comment by gabigarmus** [comment]
Now that I ran actualization, the script that visualizes entire point clouds doesn't work anymore, shows the error: Traceback (most recent call last):
  File "/home/_____/LiDAR_fog_sim/pointcloud_viewer.py", line 1880, in <module>
    app = QtGui.QApplication([])
AttributeError: module 'pyqtgraph.Qt.QtGui' has no attribute 'QApplication'

**Comment by MartinHahner** [comment]
```python
from PyQt5 import QtWidgets

app = QtWidgets.QApplication([])
```
should work.
