### ISSUE TITLE
Question about evaluation on dense fog weather in STF Dataset

### ISSUE THREAD

**Issue by n0tva1id** [MartinHahner/LiDAR_fog_sim#2]
Hi Martin,

Thank you for providing this elegant and powerful repo and I really appreciate your brilliant work!

I'm trying to reproduce the training pipeline on Seeing Through Fog Dataset. In the experimental part of the paper, there are clear weather baseline and "strongest ∩ last filter" baseline. I want to know whether clear weather baseline is evaluated on strongest return or last return of dense fog test split. I don't seem to find a description in the paper or in the supplementary materials, so sorry if I missed it.

Thank you in advance!

**Comment by MartinHahner** [comment]
Hi Qi,
thank you for your question. We always evaluate the point clouds containing the _strongest_ signal.
And it is true, we did not mention this anywhere explicitly, so thank you for pointing it out.
Greets, Martin
