### ISSUE TITLE
The wrong result of the fog_simulation.py using the kitti data.

### ISSUE THREAD

**Issue by zzqjh** [MartinHahner/LiDAR_fog_sim#7]
Thank you for your excellent contribution of this work！There is a problem when I run the fog_simulation.py to generate the fog by using the kitti dataset.
![20220505-092622](https://user-images.githubusercontent.com/56248616/166852262-49bcb7ed-9c27-4d4c-9278-40e6033aebb5.jpg)
![20220505-091752](https://user-images.githubusercontent.com/56248616/166852268-8ae804f9-d9c3-4c7d-b338-473a38f13f74.jpg)
The 1st picture is the original kitti data.
The 2nd picture is generated by the fog_simulation.py.
I wonder how can i solve the problem,thank you.

**Comment by zzqjh** [comment]
I adjusted the size of the visualization of the lidar data ,there is the picture below. what parameters should i could adjust to have a nice result? thank you.
![20220505-134015](https://user-images.githubusercontent.com/56248616/166868728-ea9febb4-86e0-4684-8ab2-c9d12b0949e3.jpg)

**Comment by MartinHahner** [comment]
I don't know what you have changed in the code.

https://github.com/MartinHahner/LiDAR_fog_sim#getting-started
If I follow the instructions above and do not make any changes to the code it looks like it is intended.

Before:
![image](https://user-images.githubusercontent.com/14181188/166893031-678b7ffc-a263-41fe-896c-7a696dcf7424.png)

After:
![image](https://user-images.githubusercontent.com/14181188/166893162-4acc913c-265f-474b-82fb-6521200f65cd.png)
