### ISSUE TITLE
Visualizing output of demo.py of OpenPCDet using a Headless Server

### ISSUE THREAD

**Issue by udacityyy** [MartinHahner/LiDAR_fog_sim#8]
Hello
First of all, thank you for these codes, they've helped me a lot.
I am a newbie to 3D object detection, I saw the demo.py code that you wrote in OpenPCDet, I have used it and got as an output the data_dict_idx.pkl and pred_dicts_idx.pkl .
Now I am trying to visualize these outputs using your pointcloud_viewer but when i choose the custom directory where i put the demo.py output, nothing shows up, I was wondering if you could help me

**Comment by MartinHahner** [comment]
Sorry, I can't help in such a general way, you need to [debug](https://www.jetbrains.com/help/pycharm/debugging-your-first-python-application.html) the code.
